name: publish

# Test and publish to choco

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  publish:
    runs-on: windows-2022
    environment: release
    needs: test

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build
        run: |
          choco pack
          choco install bottom -dv -s .
          btm -V

      - name: Publish
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/
          choco push -s https://push.chocolatey.org/
